/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package courseproject;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Josh Notter
 */
public class NewOrdersFrame extends javax.swing.JFrame {
    Connection conn;
    Statement statement;
    ResultSet resultsOfQuery = null;
    String sql;
    ResultSetMetaData meta;
    /**
     * Creates new form NewOrdersFrame
     */
    public NewOrdersFrame() {
        initComponents();
        this.conn = MainFrame.conn;
        this.statement = MainFrame.statement;
        this.resultsOfQuery = MainFrame.resultsOfQuery;
        this.sql = MainFrame.sql;
        this.meta = MainFrame.meta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderJTF = new javax.swing.JTextField();
        numJTF = new javax.swing.JTextField();
        customerJTF = new javax.swing.JTextField();
        coffeeJTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        orderJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderJTFActionPerformed(evt);
            }
        });

        jLabel1.setText("Order ID");

        jLabel2.setText("Customer ID");

        jLabel3.setText("Coffee ID");

        jLabel4.setText("Number Ordered");

        addBut.setText("Add New Order");
        addBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(orderJTF, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(customerJTF)
                            .addComponent(coffeeJTF)
                            .addComponent(numJTF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(addBut))
                .addContainerGap(543, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coffeeJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(50, 50, 50)
                .addComponent(addBut)
                .addContainerGap(310, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orderJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderJTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderJTFActionPerformed
/*public boolean validateID(String table,String vID, String cName){
    int x = 0;
    try{
            sql = "select * from "+table+" Where "+cName+" = \'"+vID+"\'";
            resultsOfQuery = statement.executeQuery(sql);
            resultsOfQuery.next();
            while (resultsOfQuery.next()){
                x++;
                System.out.println("TESTING X = "+x);
            }    
        }
         catch (SQLException ex)
        {
        System.out.println(ex.getMessage());
        }
        return x>0;
}*/
    private void addButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButActionPerformed
        // TODO add your handling code here:
        String orderID = orderJTF.getText();
        String custID = customerJTF.getText();
        String coffeeID = coffeeJTF.getText();
        double num = Double.valueOf(numJTF.getText());
        double total = 0;
        sql = "select * from Coffee Where coffeeID = \'"+coffeeID+"\'";
        try {
            resultsOfQuery = statement.executeQuery(sql);
            resultsOfQuery.next();
            String strTotal = resultsOfQuery.getObject(4).toString();
            total = Double.valueOf(strTotal);
        } catch (SQLException ex) {
            Logger.getLogger(NewOrdersFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        double grandTotal = num*total;
        
        /*String searchOrderID = (String)orderJTF.getText();
        String searchCustID = (String)customerJTF.getText();
        String searchCofID = (String)coffeeJTF.getText();
        
        boolean oIDcheck = validateID("Orders", orderID, "orderID");
        boolean cusIDcheck = validateID("Customer",custID, "customerNumber");
        boolean coffeeIDcheck = validateID("Coffee",coffeeID, "coffeeID");
        
        if(oIDcheck==true){
            InvalidEmail ieF = new InvalidEmail(NewOrdersFrame.this, true, 4);
            ieF.setVisible(true);
        }
        else if(cusIDcheck==false){
            InvalidEmail ieF = new InvalidEmail(NewOrdersFrame.this, true, 5);
            ieF.setVisible(true);
        }
        else if(coffeeIDcheck==false){
            InvalidEmail ieF = new InvalidEmail(NewOrdersFrame.this, true, 6);
            ieF.setVisible(true);
        }
        else{*/
            try {
        sql = "Insert into Orders values(\'"+orderID+"\', \'"+custID+"\', \'"+coffeeID+"\',"+num+","+grandTotal+")";
        statement.executeUpdate(sql);
            
        } catch (SQLException ex) {
            Logger.getLogger(NewCustFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        //}
        
        
        
    }//GEN-LAST:event_addButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewOrdersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewOrdersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewOrdersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewOrdersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewOrdersFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBut;
    private javax.swing.JTextField coffeeJTF;
    private javax.swing.JTextField customerJTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField numJTF;
    private javax.swing.JTextField orderJTF;
    // End of variables declaration//GEN-END:variables
}
