/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package courseproject;

import static java.lang.String.format;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author Josh Notter
 */
public class OrdersFrame extends javax.swing.JFrame {
    Connection conn;
    Statement statement;
    ResultSet resultsOfQuery = null;
    String sql;
    ResultSetMetaData meta;
    /**
     * Creates new form OrdersFrame
     */
    public OrdersFrame() {
        initComponents();
        this.conn = MainFrame.conn;
        this.statement = MainFrame.statement;
        this.resultsOfQuery = MainFrame.resultsOfQuery;
        this.sql = MainFrame.sql;
        this.meta = MainFrame.meta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ordersDisplayTable = new javax.swing.JTable();
        orderDisplayBut = new javax.swing.JButton();
        searchBut = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ordersDisplayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Customer ID", "Coffee ID", "Num Ordered", "Total"
            }
        ));
        ordersDisplayTable.setShowGrid(true);
        jScrollPane1.setViewportView(ordersDisplayTable);

        orderDisplayBut.setText("Display Data");
        orderDisplayBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderDisplayButActionPerformed(evt);
            }
        });

        searchBut.setText("Search by Customer ID");
        searchBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(orderDisplayBut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderDisplayBut)
                    .addComponent(searchBut)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orderDisplayButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderDisplayButActionPerformed
        // TODO add your handling code here:
        try{
            //StringBuilder strb = new StringBuilder(); test code
            sql = "select * from Orders";
            resultsOfQuery = MainFrame.statement.executeQuery(sql);
            int x = 0;
            while (resultsOfQuery.next()){
                ordersDisplayTable.setValueAt(resultsOfQuery.getObject(1), x, 0);
                ordersDisplayTable.setValueAt(resultsOfQuery.getObject(2), x, 1);
                ordersDisplayTable.setValueAt(resultsOfQuery.getObject(3), x, 2);
                ordersDisplayTable.setValueAt(format("%.2f",resultsOfQuery.getObject(4)), x, 3);
                ordersDisplayTable.setValueAt(format("%.2f",resultsOfQuery.getObject(5)), x, 4);
                x++;
            }
        }
        catch (SQLException ex)
        {
        System.out.println(ex.getMessage());
        }
        
    }//GEN-LAST:event_orderDisplayButActionPerformed

    private void searchButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButActionPerformed
 try{
            //StringBuilder strb = new StringBuilder(); test code
            sql = "select * from Orders";
            resultsOfQuery = MainFrame.statement.executeQuery(sql);
            int x = 0;
            while (resultsOfQuery.next()){
                ordersDisplayTable.setValueAt(resultsOfQuery.getObject(1), x, 0);
                ordersDisplayTable.setValueAt(resultsOfQuery.getObject(2), x, 1);
                ordersDisplayTable.setValueAt(resultsOfQuery.getObject(3), x, 2);
                ordersDisplayTable.setValueAt(format("%.2f",resultsOfQuery.getObject(4)), x, 3);
                ordersDisplayTable.setValueAt(format("%.2f",resultsOfQuery.getObject(5)), x, 4);
                x++;
            }
        }
        catch (SQLException ex)
        {
        System.out.println(ex.getMessage());
        }
 // TODO add your handling code here:
        String searchID;
        int x = 0;
        searchID = (String)jTextField1.getText();
        try{
            sql = "select * from Orders Where custID = \'"+searchID+"\'";
            

            resultsOfQuery = statement.executeQuery(sql);
            resultsOfQuery.next();
            while (resultsOfQuery.next()){
                ordersDisplayTable.setValueAt(resultsOfQuery.getObject(1), x, 0);
                ordersDisplayTable.setValueAt(resultsOfQuery.getObject(2), x, 1);
                ordersDisplayTable.setValueAt(resultsOfQuery.getObject(3), x, 2);
                ordersDisplayTable.setValueAt(format("%.2f",resultsOfQuery.getObject(4)), x, 3);
                ordersDisplayTable.setValueAt(format("%.2f",resultsOfQuery.getObject(5)), x, 4);
                x++;
            }
                
            
        }
         catch (SQLException ex)
        {
        System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_searchButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrdersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrdersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrdersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrdersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrdersFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton orderDisplayBut;
    private javax.swing.JTable ordersDisplayTable;
    private javax.swing.JButton searchBut;
    // End of variables declaration//GEN-END:variables
}
